2018-12-03 16:05:39,565 - detector_diagnosis_list.py - [line:68] - ERROR - when reaching interinfo, 'Postgres' object has no attribute 'cursor'
2018-12-03 16:05:39,565 - detector_diagnosis_list.py - [line:72] - ERROR - when calling postgresql, 'Postgres' object has no attribute 'close'
2018-12-03 16:05:39,566 - detector_diagnosis_list.py - [line:41] - ERROR - when reaching detector_all, 'Oracle' object has no attribute 'cursor'
2018-12-03 16:05:39,566 - detector_diagnosis_list.py - [line:45] - ERROR - when calling oracle, 'Oracle' object has no attribute 'close'
2018-12-03 16:10:15,495 - detector_diagnosis_list.py - [line:72] - ERROR - when reaching interinfo, 'psycopg2.extensions.cursor' object has no attribute 'call_pg_data'
2018-12-03 16:10:43,080 - detector_diagnosis_list.py - [line:72] - ERROR - when reaching interinfo, 'psycopg2.extensions.cursor' object has no attribute 'call_pg_data'
2018-12-03 19:30:21,917 - detector_disgnosis_detail.py - [line:46] - ERROR - when calling oracle, 'Oracle' object has no attribute 'close'
2018-12-03 20:48:14,977 - detector_disgnosis_detail.py - [line:46] - ERROR - when calling oracle, 'Oracle' object has no attribute 'close'
2018-12-03 20:48:28,276 - detector_disgnosis_detail.py - [line:46] - ERROR - when calling oracle, 'Oracle' object has no attribute 'close'
2018-12-03 20:52:06,509 - detector_disgnosis_detail.py - [line:46] - ERROR - when calling oracle, 'Oracle' object has no attribute 'close'
